//------------------------------------------------------------------------------
// <auto-generated>This code was generated by a tool.</auto-generated>
//------------------------------------------------------------------------------
namespace BlackCatPomodoro.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        public static Settings Default { get { return defaultInstance; } }

        [global::System.Configuration.UserScopedSettingAttribute()][global::System.Diagnostics.DebuggerNonUserCodeAttribute()][global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string Theme { get { return ((string)(this["Theme"])); } set { this["Theme"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()][global::System.Diagnostics.DebuggerNonUserCodeAttribute()][global::System.Configuration.DefaultSettingValueAttribute("Microsoft YaHei UI, 9pt")]
        public string AppFont { get { return ((string)(this["AppFont"])); } set { this["AppFont"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()][global::System.Diagnostics.DebuggerNonUserCodeAttribute()][global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SoundMode { get { return ((int)(this["SoundMode"])); } set { this["SoundMode"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()][global::System.Diagnostics.DebuggerNonUserCodeAttribute()][global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SoundFilePath { get { return ((string)(this["SoundFilePath"])); } set { this["SoundFilePath"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()][global::System.Diagnostics.DebuggerNonUserCodeAttribute()][global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SoundDevice { get { return ((int)(this["SoundDevice"])); } set { this["SoundDevice"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()][global::System.Diagnostics.DebuggerNonUserCodeAttribute()][global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotifyToast { get { return ((bool)(this["NotifyToast"])); } set { this["NotifyToast"] = value; } }
    }
}
